<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="GGN000174216001" ignored="0" name="CreateCustomerAPITest" tests="4" failures="1" timestamp="07 Mar 2020 19:31:26 GMT" time="9.176" errors="0">
  <testcase name="validateCreateCustomerAPIWithInvalidSecretkey" time="6.499" classname="com.restassured.testcases.CreateCustomerTest">
    <failure type="java.lang.AssertionError" message="expected [200] but found [401]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [401]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at com.restassured.testcases.CreateCustomerTest.validateCreateCustomerAPIWithInvalidSecretkey(CreateCustomerTest.java:38)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
]]>
    </failure>
  </testcase> <!-- validateCreateCustomerAPIWithInvalidSecretkey -->
  <testcase name="validateCreateCustomerAPIWithValidSecretkey" time="1.771" classname="com.restassured.testcases.CreateCustomerTest"/>
  <testcase name="validateCreateCustomerAPIWithValidSecretkey" time="2.132" classname="com.restassured.testcases.CreateCustomerTest"/>
  <testcase name="validateCreateCustomerAPIWithValidSecretkey" time="2.594" classname="com.restassured.testcases.CreateCustomerTest"/>
</testsuite> <!-- CreateCustomerAPITest -->
